// Metadata doesn't need to be in layout
// export const metadata = {
// 	title: 'Next.js - About us',
// 	description: 'Generated by Next.js',
// }
  
export default function AboutUsLayout({	children, }: { children: React.ReactNode }) {
	return (
		<div>
			{children}
			&copy; Generated by Next JS
		</div>
	)
}